name: xpe-hubServices-deploy
on:
    workflow_dispatch:

jobs:
    CI-Dev:
        permissions:
            contents: 'read'
            id-token: 'write'
            
        uses: killerdaemon01/gh-template2/.github/workflows/ci_javascript.yaml@master
        with: 
            keyvaultfile: keyvaultvars.json
            environment: development
            tag: ${{github.run_id}}
        secrets: inherit
    
    CI-Test:
        permissions:
            contents: 'read'
            id-token: 'write'
        needs: CI-Dev    
        uses: killerdaemon01/gh-template2/.github/workflows/ci_javascript.yaml@master
        with: 
            keyvaultfile: keyvaultvars.json
            environment: test
            tag: ${{github.run_id}}
        secrets: inherit
  
    Deploy-Dev:
        needs: CI-Dev
        permissions:
            contents: 'read'
            id-token: 'write'
        uses: killerdaemon01/gh-template2/.github/workflows/cd_javascript.yaml@master
        with:
            keyvaultfile: keyvaultvars.json
            tag: ${{github.run_id}}
            environment: development
            slot_name: production
            swap_slot: false
        secrets: inherit
        
    Deploy-Test:
        needs: CI-Dev
        permissions:
            contents: 'read'
            id-token: 'write'
        uses: killerdaemon01/gh-template2/.github/workflows/cd_javascript.yaml@master
        with:
            keyvaultfile: keyvaultvars.json
            tag: ${{github.run_id}}
            environment: test
            slot_name: stage
            swap_slot: true
        secrets: inherit
