name: Fetch secrets and replace them on json file

on:
  workflow_dispatch:
    inputs:
      keyvaultname:
        description: Name of the keyvault
        type: string
        required: false
        default: 'kv29017'

      configfilename:
        description: Configfile
        type: string
        required: false
        default: 'GlobalConfig.json'


jobs:
  Secrets:
    permissions:
      contents: 'read'
      id-token: 'write'
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true 
      - name: Find var file name
        shell: bash
        run: |
          file=$(find . -name ${{inputs.configfilename}})
          echo "$file"
          echo "kv_file="$file"" >> $GITHUB_ENV

      - name: Run Azure PowerShell script
        uses: azure/powershell@v1
        with:
          inlineScript: |
                      $hashtable = Get-Content ${{env.kv_file}} | ConvertFrom-Json -AsHashtable

                      # Accessing values from the hashtable
                      $url = $hashtable.cdt.url
                      $users = $hashtable.cdt.users

                      foreach ($user in $users.GetEnumerator()) {
                          $userId = $user.Value.userId
                          $key = (Get-AzKeyVaultSecret -VaultName kv29017 -Name $userId -AsPlainText)
                          Write-Output $userId
                          Write-Output $key
                          Write-Output "-------------------------------------------------------------------------------------"
                          #echo "::add-mask::$key"
                          Write-Output "$userId=$($key)" >> $Env:GITHUB_OUTPUT
                      }
          azPSVersion: "latest"
      - name: Print json file
        shell: pwsh
        run: |
          Get-Content ${{env.kv_file}}
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["**/*.json"]'
          
      - name: Print json file
        shell: pwsh
        run: |
          Get-Content ${{env.kv_file}}
      - name: Azure logout
        run: |
          az logout
