name: Fetch secrets and replace tokens
on:
  workflow_dispatch

jobs:
  Secrets:
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: killerdaemon01/gh-template2/.github/workflows/template.yaml@master
    with:
      environment: development
      keyvaultname: kv29017
      configfilename: 'GlobalConfig.json'
