name: Fetch secrets and replace them on json file

on:
  workflow_dispatch:
    inputs:
      keyvaultname:
        description: Name of the keyvault
        type: string
        required: false
        default: 'kv29017'

      configfilename:
        description: Configfile
        type: string
        required: false
        default: 'GlobalConfig.json'


jobs:
  Secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3
      # - name: Azure Login
      #   uses: azure/login@v1
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Find var file name
        shell: bash
        run: |
          file=$(find . -name ${{inputs.configfilename}})
          echo "$file"
          echo "kv_file="$file"" >> $GITHUB_ENV
      - name: Get secrets
        run: |
          $hashtable = Get-Content '.\global2.json' | ConvertFrom-Json -AsHashtable

          # Accessing values from the hashtable
          $url = $hashtable.cdt.url
          $users = $hashtable.cdt.users

          # Printing the hashtable
          Write-Output "URL: $url"
          Write-Output "Users: $users"

          foreach ($user in $users.GetEnumerator()) {
              $userName = $user.Key
              $userId = $user.Value.userId
              $key = (Get-AzKeyVaultSecret -VaultName kv29017 -Name $userId -AsPlainText)
              Write-Output $userId
              Write-Output $key
              Write-Output "-------------------------------------------------------------------------------------"
          }

        
